# .goreleaser.yml
# before:
#   hooks:
#     - go mod tidy
#     - go generate ./...

builds:
  - main: ./goreleasershim
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64

# dockers:
#   - image_templates: ["ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-amd64"]
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#     - --platform=linux/amd64
#     - --label=org.opencontainers.image.title={{ .ProjectName }}
#     - --label=org.opencontainers.image.description={{ .ProjectName }}
#     - --label=org.opencontainers.image.url=https://github.com/krzko/{{ .ProjectName }}
#     - --label=org.opencontainers.image.source=https://github.com/krzko/{{ .ProjectName }}
#     - --label=org.opencontainers.image.version={{ .Version }}
#     - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#     - --label=org.opencontainers.image.revision={{ .FullCommit }}
#     - --label=org.opencontainers.image.licenses=MIT
#   - image_templates: ["ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
#     goarch: arm64
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#     - --platform=linux/arm64/v8
#     - --label=org.opencontainers.image.title={{ .ProjectName }}
#     - --label=org.opencontainers.image.description={{ .ProjectName }}
#     - --label=org.opencontainers.image.url=https://github.com/krzko/{{ .ProjectName }}
#     - --label=org.opencontainers.image.source=https://github.com/krzko/{{ .ProjectName }}
#     - --label=org.opencontainers.image.version={{ .Version }}
#     - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#     - --label=org.opencontainers.image.revision={{ .FullCommit }}
#     - --label=org.opencontainers.image.licenses=MIT

# docker_manifests:
#   - name_template: ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}
#     image_templates:
#     - ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-amd64
#     - ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-arm64v8
#   - name_template: ghcr.io/krzko/{{ .ProjectName }}:latest
#     image_templates:
#     - ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-amd64
#     - ghcr.io/krzko/{{ .ProjectName }}:{{ .Version }}-arm64v8

archives:
  - files:
    - src: 'library/*.sh'
      dst: library


# checksum:
#   name_template: '{{.ProjectName}}_checksums.txt'

# snapshot:
#   name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

brews:
  - name: opentelemetry-shell
    tap:
      owner: 'krzko'
      name: 'homebrew-tap'
    homepage: https://github.com/krzko/opentelemetry-shell
    description: "OpenTelemetry functions for shells"
    install: |
      system "make" "install"
    test: |
      system "make" "version"
