FROM alpine:3

RUN apk add --update-cache bash curl jq

COPY examples /root/opentelemetry-shell/examples/
COPY library /root/opentelemetry-shell/library/

WORKDIR /root/opentelemetry-shell/examples

ENTRYPOINT ["bash"]
