FROM debian:11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

COPY examples /root/opentelemetry-shell/examples/
COPY library /root/opentelemetry-shell/library/

WORKDIR /root/opentelemetry-shell/examples

ENTRYPOINT ["bash"]
